version: '3.8'

services:
  web:
    image: jayadeep3/yii2-app:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: yii2app
      DB_USERNAME: root
      DB_PASSWORD: secret

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: yii2app
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
