version: "3.8"
services:
  yii2-app:
    build: /yii2-app .
    image: jayadeep3/yii2-app:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      retries: 3
  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    deploy:
      mode: global
    networks:
      - app-network
networks:
  app-network:
    driver: overlay
