---
- hosts: all
  become: yes
  tasks:
    - name: Deploy Yii2 app stack
      shell: docker stack deploy -d -c /yii2-app/docker/docker-compose.yml yii2_app
      args:
        chdir: /yii2-app/docker
