---
- name: Install Docker 
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    - name: Build Docker image from Dockerfile
      docker_image:
        build:
          path: /docker/Dockerfile
        name: your-dockerhub-username/yii2-app
        tag: latest
        state: present
