name: Deploy Yii2 App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Push Docker Image
      run: |
        cd docker
        docker build -t "${{ secrets.DOCKER_USERNAME }}"/yii2-app:latest .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push "${{ secrets.DOCKER_USERNAME }}"/yii2-app:latest

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd ~/yii2-docker-app
          docker stack deploy -c docker/docker-compose.yml yii2_app
